import { ServiceItem, ProjectItem, TestimonialItem, FAQItem, TechItem, ProcessStep, WhyUsItem } from '@/types';

export const SITE_CONFIG = {
  name: 'Webbound',
  tagline: 'High-Craft Digital Engineering & Creative Direction',
  description: 'Independent creative engineer & designer crafting bespoke, ultra-fast, and visually captivating flagship web experiences for ambitious brands.',
  url: 'https://webbound-nine.vercel.app',
  email: 'hello@webboundstudios.com',
  location: 'India',
  stats: [
    { label: 'Bespoke Projects', value: 65, suffix: '+' },
    { label: 'Sub-Second Speed Target', value: 100, suffix: '%' },
    { label: 'Client Satisfaction', value: 99, suffix: '%' },
    { label: 'Years of Craft', value: 6, suffix: '+' },
  ]
};

export const SERVICES: ServiceItem[] = [
  {
    id: 'type-1-single-page-static',
    title: 'Type 1: Single-Page Business Website',
    subtitle: 'Fast, Responsive & Professional Online Presence',
    description:
      'A modern single-page website designed for startups, local businesses, and professionals. Optimized for speed, mobile devices, and search engines while showcasing your brand and essential business information.',
    iconName: 'Layout',
    tierBadge: 'Type 1 Offering',
    deliverables: [
      'Custom Responsive Landing Page',
      'Business Information & Services',
      'Contact Form & Google Maps Integration',
      'Performance & Basic SEO Optimization',
    ],
    tags: ['Responsive', 'Fast Loading', 'SEO Ready', 'Static Website'],
    accentColor: '#C5F52A',
  },

  {
    id: 'type-2-single-page-cms',
    title: 'Type 2: Dynamic CMS Website',
    subtitle: 'Manage Your Website Without Writing Code',
    description:
      'A dynamic website powered by a headless CMS, allowing you to easily manage blogs, projects, services, galleries, and media without needing developer assistance.',
    iconName: 'Edit3',
    tierBadge: 'Type 2 Offering',
    deliverables: [
      'Headless CMS Integration',
      'Blog & Article Management',
      'Portfolio / Project Management',
      'Media & Document Uploads',
      'Dynamic Content Updates',
      'SEO Ready',
    ],
    tags: ['CMS', 'Dynamic Content', 'SEO Ready', 'Media Management'],
    accentColor: '#C5F52A',
  },

  {
    id: 'type-3-multipage-cms',
    title: 'Type 3: Premium CMS Platform',
    subtitle: 'Custom Admin Dashboard & Complete Content Management',
    description:
      'A premium multi-page website with a fully custom admin dashboard tailored to your business. Manage your content through a clean, intuitive interface while updates are securely synchronized with a headless CMS in real time.',
    iconName: 'Layers',
    tierBadge: 'Most Popular',
    deliverables: [
      'Multi-Page Responsive Website',
      'Custom Admin Dashboard',
      'Secure Admin Authentication',
      'Blog & Article Management',
      'Portfolio & Project Management',
      'Media Library & File Uploads',
      'Services, Team & Testimonials Management',
      'SEO Metadata Controls',
      'Real-Time Content Updates',
    ],
    tags: [
      'Custom Dashboard',
      'CMS',
      'Multi-Page',
      'Secure',
      'SEO Optimized',
      'Scalable',
    ],
    accentColor: '#C5F52A',
  },

  {
    id: 'type-4-fullstack-custom',
    title: 'Type 4: Custom Full-Stack Web Application',
    subtitle: 'Built Around Your Business Workflow',
    description:
      'Custom web applications built specifically for your business requirements with secure authentication, databases, APIs, payment systems, dashboards, and advanced business logic.',
    iconName: 'Database',
    tierBadge: 'Enterprise Solution',
    deliverables: [
      'Custom Backend Development',
      'REST API / GraphQL API',
      'Database Architecture (MongoDB / PostgreSQL)',
      'User Authentication & Role Management',
      'Admin Dashboard',
      'Payment Gateway Integration',
      'Third-Party API Integrations',
      'Custom Business Workflows',
      'Deployment & Production Setup',
    ],
    tags: [
      'Full-Stack',
      'Custom APIs',
      'Authentication',
      'Database',
      'Enterprise',
    ],
    accentColor: '#C5F52A',
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'the-trusted-wall',
    title: 'The Trusted Wall Architecture',
    category: 'Architecture & Luxury Interiors',
    year: '2026',
    tier: 'Type 3: Multi-Page Dynamic CMS Platform',
    description: 'A flagship architectural and luxury interior design studio platform for Ar. Himanshu Gautam, built under our Type 3 package with Sanity CMS for dynamic project creation, blog updates, and spatial galleries.',
    longDescription: 'The Trusted Wall Architecture required an immersive digital presence capable of showcasing high-end residential and commercial architectural achievements with sub-second page performance. Built under Webbound’s Type 3 Multi-Page CMS tier, we integrated Sanity Headless CMS, spatial layout grids, and bespoke fluid motion physics to ensure Ar. Himanshu Gautam’s studio presents authority and elegance at scale.',
    challenge: 'Architectural portfolios often suffer from heavy high-resolution media leading to slow load times and layout shifts. The challenge was rendering uncompromised, razor-sharp gallery imagery while maintaining sub-second Core Web Vitals across all device viewports.',
    solution: 'We engineered an edge-cached Next.js image pipeline paired with Sanity CMS, custom webp compression, and GSAP scroll-triggered motion physics. Layout shifts were completely eliminated while delivering fluid 60 FPS transitions.',
    role: 'Lead Creative Engineer & Architect',
    client: 'The Trusted Wall Studio (Agra)',
    impact: 'Type 3 Multi-Page CMS Flagship',
    image: 'https://ik.imagekit.io/dhyh95euj/webbound/TrustedWall.webp',
    tags: ['Type 3 Package', 'Sanity CMS', 'React 19', 'GSAP', 'Vite'],
    link: 'https://thetrustedwall.com/',
    featured: true,
  },
  {
    id: 'tdid-interiors',
    title: 'TDID Interiors Luxury Studio',
    category: 'Luxury Interior Design & Turnkey',
    year: '2026',
    tier: 'Type 1: Single-Page Flagship',
    description: 'A bespoke single-page luxury interior design portal for TDID Interiors in Greater Noida, built under our Type 1 package featuring custom modular kitchen lookbooks and Lenis smooth scroll.',
    longDescription: 'TDID Interiors wanted a ultra-clean, tactile digital experience to capture high-ticket turnkey interior design inquiries across Greater Noida and Delhi NCR. Under Webbound’s Type 1 Single-Page Flagship tier, we crafted a high-frictionless spatial journey with smooth Lenis physics, interactive lookbooks, and instant inquiry forms.',
    challenge: 'Standing out in a crowded interior design market required moving away from cookie-cutter templates to deliver an editorial-grade interactive experience that builds immediate trust with luxury homeowners.',
    solution: 'We designed a custom editorial theme with rich typography pairing (Clash Display & Satoshi), micro-animations, and GPU-accelerated smooth scrolling that guides high-intent visitors directly to the inquiry funnel.',
    role: 'Digital Engineer & UI Director',
    client: 'TDID Interiors (Delhi NCR)',
    impact: 'Type 1 Single-Page Flagship',
    image: 'https://ik.imagekit.io/dhyh95euj/webbound/Tdid-interiors.webp',
    tags: ['Type 1 Package', 'React 19', 'Lenis Scroll', 'GSAP', 'Formspree'],
    link: 'https://tdidinteriors.com/',
    featured: true,
  },
  {
    id: 'studio-kalagya',
    title: 'Studio Kalagya Architecture & Interiors',
    category: 'Architecture & Spatial Interiors',
    year: '2026',
    tier: 'Type 2: Dynamic CMS Website',
    description: 'A dynamic architecture and interior design CMS portal for Studio Kalagya in Jabalpur, featuring flexible project galleries, custom interior artwork showcases, and headless content management.',
    longDescription: 'Studio Kalagya required a dynamic digital showcase to manage and highlight their architectural projects, interior design transformations, and custom material installations across Jabalpur and Central India. Built under Webbound’s Type 2 Dynamic CMS tier, the platform enables continuous content management while delivering organic design aesthetics and sub-second performance.',
    challenge: 'Architectural and interior design portfolios require frequently updating high-resolution spatial imagery and custom art installations without compromising mobile load times, visual crispness, or site performance.',
    solution: 'We engineered a dynamic headless CMS pipeline paired with high-legibility spatial typography, fluid micro-interactions, and optimized media delivery to empower real-time portfolio management.',
    role: 'Lead Digital Engineer & UI Architect',
    client: 'Studio Kalagya (Jabalpur, MP)',
    impact: 'Type 2 Dynamic CMS Portal',
    image: 'https://framerusercontent.com/images/KSmNZNCybUljPNMsMJbAmkxK4M.jpg',
    tags: ['Type 2 Package', 'Headless CMS', 'Architecture', 'React 19', 'GSAP'],
    link: 'https://www.studiokalagya.in/',
    featured: true,
  },
  {
    id: 'forever-interior',
    title: 'Forever Interior Spatial Studio',
    category: 'Modular Kitchen & Spatial Interiors',
    year: '2026',
    tier: 'Type 3: Multi-Page Dynamic CMS Platform',
    description: 'A multi-page luxury interior design and modular kitchen platform for Forever Interior in Jaipur, built under our Type 3 package with headless CMS for dynamic project lookbooks, wardrobe showcases, and spatial galleries.',
    longDescription: 'Forever Interior is a premier modular kitchen and luxury interior design studio based in Jaipur, Rajasthan, founded by Raj Suroliya. Webbound engineered a high-craft Type 3 multi-page digital flagship with headless CMS integration to showcase their extensive modular kitchen layouts, wardrobe collections, and living space transformations while streamlining high-ticket client inquiries.',
    challenge: 'Managing and displaying extensive multi-page modular kitchen designs and high-resolution spatial interior galleries without compromising page load speeds, visual crispness, or mobile responsiveness.',
    solution: 'We built a multi-page Next.js platform powered by headless CMS, edge-cached media pipelines, Lenis smooth scroll physics, custom spatial typography, and an interactive quote request funnel tailored for luxury homeowners.',
    role: 'Lead Digital Engineer & UI Architect',
    client: 'Forever Interior (Jaipur, Rajasthan)',
    impact: 'Type 3 Multi-Page CMS Flagship',
    image: 'https://foreverinterio.in/wp-content/uploads/2021/01/living-space.jpg',
    tags: ['Type 3 Package', 'Sanity CMS', 'React 19', 'GSAP', 'Next.js 15'],
    link: 'https://foreverinterio.in/',
    featured: true,
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    step: '01',
    title: 'Rapid Discovery & Strategy',
    subtitle: 'Deconstructing brand essence & technical requirements',
    description: 'I analyze your goals 1-on-1 to establish the site architecture, typography, and motion plan within 24 hours.',
    duration: 'Day 1 – 2',
    details: ['Brand Essence Audit', 'Architecture Blueprint', 'Typography & Palette Selection', '1-Year Maintenance Plan'],
  },
  {
    step: '02',
    title: 'Bespoke UI/UX & Motion Prototyping',
    subtitle: 'Designing for clarity & immediate visual impact',
    description: 'Every layout grid, component, and animation curve is custom-designed down to the pixel for your brand.',
    duration: 'Days 3 – 5',
    details: ['Desktop & Mobile Prototypes', 'Custom Design System', 'Micro-Interactions', 'CMS Structure Blueprint'],
  },
  {
    step: '03',
    title: 'Precision Engineering & CMS Integration',
    subtitle: 'Writing clean code with 60 FPS fluidity',
    description: 'I build your platform using Next.js 15, React 19, GSAP, and Headless CMS for rapid dynamic content updates.',
    duration: 'Days 6 – 9',
    details: ['Component Architecture', 'GSAP ScrollTrigger Logic', 'Sanity/Headless CMS Integration', 'Mobile Optimization'],
  },
  {
    step: '04',
    title: 'Performance Tuning & Speed Audit',
    subtitle: 'Achieving sub-second load times',
    description: 'Rigorously tested across real devices and network speeds to ensure instant hydration, zero layout shift, and SEO readiness.',
    duration: 'Days 10 – 12',
    details: ['Core Web Vitals Audit', 'Cross-Device Testing', 'SEO Metadata & Schema', 'Content Upload Training'],
  },
  {
    step: '05',
    title: 'Final Launch & 1-Year Free Maintenance',
    subtitle: 'Deploying to global edge CDN with ongoing support',
    description: 'Production deployment with 1 Full Year of Included Free Maintenance & Free Small Content Changes.',
    duration: 'Day 14 (Handover)',
    details: ['Vercel Edge Deployment', 'Complete Site Handover', '1 Year Free Maintenance', 'Free Small Content Updates'],
  },
];

export const WHY_US: WhyUsItem[] = [
  {
    id: 'rapid-handover',
    number: '01',
    title: 'Rapid 1–2 Week Handover',
    description: 'No waiting months for a website. Most custom platforms are engineered, tested, and handed over within 1 to 2 weeks (3 to 14 days).',
    highlight: '1-2 Week Handover',
  },
  {
    id: 'free-maintenance',
    number: '02',
    title: '1 Year Free Maintenance & Edits',
    description: 'Every project comes with 1 Full Year of Included Free Maintenance and Free Small Content Changes (text, image, blog updates).',
    highlight: '1-Year Free Support',
  },
  {
    id: 'no-templates',
    number: '03',
    title: 'Zero Templates. 100% Handcrafted.',
    description: 'I reject generic templates and agency bloat. Every layout grid, typography pair, and scroll animation is handcrafted specifically for your brand.',
    highlight: 'Handcrafted Quality',
  },
  {
    id: 'direct-collaboration',
    number: '04',
    title: '1-on-1 Direct Collaboration',
    description: 'No middle managers or miscommunications. You work directly with the lead engineer & designer building your project.',
    highlight: 'Direct Founder Access',
  },
];

export const TECH_STACK: TechItem[] = [
  { id: 'nextjs', name: 'Next.js 15', category: 'frontend', icon: 'Globe', level: 'App Router / Server Components', description: 'React Framework for Production' },
  { id: 'react', name: 'React 19', category: 'frontend', icon: 'Atom', level: 'Concurrent Mode & Hooks', description: 'UI Library' },
  { id: 'typescript', name: 'TypeScript', category: 'frontend', icon: 'Code', level: 'Strict Type System', description: 'Type-Safe Javascript' },
  { id: 'tailwind', name: 'Tailwind CSS v4', category: 'frontend', icon: 'Wind', level: 'CSS Variables & Utility Classes', description: 'Styling Engine' },
  { id: 'gsap', name: 'GSAP Premium', category: 'animation', icon: 'Zap', level: 'ScrollTrigger, SplitText, MorphSVG, Inertia', description: 'Animation Standard' },
  { id: 'framer', name: 'Framer Motion', category: 'animation', icon: 'Layers', level: 'Gestures & Micro-Interactions', description: 'React Motion Library' },
  { id: 'lenis', name: 'Lenis Scroll', category: 'animation', icon: 'MousePointer', level: 'Smooth Scroll & RAF Sync', description: 'Scroll Physics' },
  { id: 'three', name: 'Canvas 2D / WebGL', category: 'animation', icon: 'Box', level: 'Interactive Lighting & Particle Engine', description: 'Graphics Engine' },
  { id: 'zustand', name: 'Zustand', category: 'tools', icon: 'Cpu', level: 'Global Reactive State', description: 'State Management' },
  { id: 'shadcn', name: 'Shadcn UI', category: 'frontend', icon: 'Component', level: 'Accessible Primitive Components', description: 'UI System' },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: '1',
    quote: 'Working with Webbound was a smooth experience from start to finish. They understood how we wanted to present our architectural work and delivered a fast, modern website that reflects our brand perfectly. The CMS also makes updating projects much easier.',
    author: 'Ar. Himanshu Gautam',
    role: 'Founder & Lead Architect',
    company: 'The Trusted Wall (Agra)',
    metrics: 'Type 3 Architecture Platform',
  },
  {
    id: '2',
    quote: 'We wanted a clean, premium website that would showcase our interior projects without feeling cluttered. Webbound delivered exactly that. The site feels fast, looks great on every device, and has received positive feedback from our clients.',
    author: 'Ripul Taneja',
    role: 'Founder & Principal Designer',
    company: 'TDID Interiors (Delhi NCR)',
    metrics: 'Type 1 Interior Platform',
  },
  {
    id: '3',
    quote: "The entire process was well organized and collaborative. Webbound paid attention to the details, kept us updated throughout the project, and built a website that represents our studio in a professional way. We're very happy with the final result.",
    author: 'Ar. Akshay Jain',
    role: 'Founder & Principal Architect of Kalagya',
    company: 'Studio Kalagya (Jabalpur)',
    metrics: 'Type 2 Architecture Platform',
  },
  {
    id: '4',
    quote: "Webbound created a website that showcases our interior projects in a clean and professional way. It has become much easier for potential clients to explore our work, and we've received great feedback on the design, speed, and overall experience.",
    author: 'Raj Suroliya',
    role: 'Founder of Company',
    company: 'Forever Interior (Jaipur)',
    metrics: 'Type 3 Interior Platform',
  },
];

export const FAQS: FAQItem[] = [
  {
    id: 'timeline',
    question: 'How fast do you build and handover websites?',
    answer: 'I build and deliver websites in days, not months! Most projects are completely handed over within 1 to 2 weeks (3 to 14 days). Plus, every website includes 1 Full Year of Free Maintenance & Free Small Content Changes.',
    category: 'Process',
  },
  {
    id: 'maintenance',
    question: 'What is included in the 1-Year Free Maintenance guarantee?',
    answer: 'Every website includes 1 Full Year of Included Free Maintenance and Free Small Content Changes (updating text, swapping images, blog/project formatting, performance monitoring, and technical maintenance) at zero extra cost!',
    category: 'Services',
  },
  {
    id: 'pricing',
    question: 'What service tiers and packages do you offer?',
    answer: 'I offer 4 distinct service tiers tailored to your needs: Type 1 (Single-Page Business Website), Type 2 (Dynamic CMS Website for blogs, projects & media), Type 3 (Multi-Page Dynamic CMS Platform), and Type 4 (Custom Full-Stack Web Application with custom backend logic & database architecture).',
    category: 'Engagement',
  },
  {
    id: 'performance',
    question: 'How do you ensure sub-second load times across mobile networks?',
    answer: 'I enforce strict GPU hardware acceleration, RAF loop synchronization, dynamic code splitting, asset preloading, and edge CDN compression so animations never compromise speed.',
    category: 'Technical',
  },
  {
    id: 'collaboration',
    question: 'How do we collaborate during the project?',
    answer: 'You work directly 1-on-1 with me through Figma reviews, staging preview links, and direct WhatsApp/Slack communication. No middle managers or delays.',
    category: 'Process',
  },
];

export const NAV_LINKS = [
  { label: 'About', href: '/#about' },
  { label: 'Services', href: '/#services' },
  { label: 'Work', href: '/#projects' },
  { label: 'Process', href: '/#process' },
  { label: 'Tech Stack', href: '/#tech' },
  { label: 'Motion Lab', href: '/animations' },
  { label: 'Testimonials', href: '/#testimonials' },
  { label: 'FAQ', href: '/#faq' },
];
